
name = "lunaria"
compatibility_date = "2023-07-10
"


[build]
command = "npm run build"

[site]
bucket = "./build/client"

[functions]
directory = "functions"

pages_build_output_dir = "./build/client"



# Vos KV namespaces (facultatif)
kv_namespaces = [
  { binding = "portfolio_MY_SS", id = "6bbc57c2ccdd498a88e8c223343cbdb6" }
]


